drop user Takecar cascade;

CREATE USER Takecar PROFILE "DEFAULT" IDENTIFIED BY joly902f ACCOUNT UNLOCK;
GRANT SYSDBA TO Takecar WITH ADMIN OPTION;
GRANT SYSOPER TO Takecar WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO Takecar;
GRANT "AUTHENTICATEDUSER" TO Takecar;
GRANT "CONNECT" TO Takecar;
GRANT "DBA" TO Takecar;
GRANT "EXP_FULL_DATABASE" TO Takecar;
GRANT "IMP_FULL_DATABASE" TO Takecar;
